# Generated by Django 5.0.2 on 2024-04-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmanager',
            name='detail_requestmanager',
            field=models.CharField(max_length=255),
        ),
    ]
