# Generated by Django 5.0.2 on 2024-04-20 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_requestmanager_detail_requestmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDetail',
            fields=[
                ('id_requestdetail', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=255, null=True)),
                ('originLat', models.FloatField(default=0.0)),
                ('originLng', models.FloatField(default=0.0)),
                ('destination', models.CharField(max_length=255, null=True)),
                ('destinationLat', models.FloatField(default=0.0)),
                ('destinationLng', models.FloatField(default=0.0)),
                ('current', models.CharField(max_length=255, null=True)),
                ('currentLat', models.FloatField(default=0.0)),
                ('currentLng', models.FloatField(default=0.0)),
                ('distance', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('points', models.CharField(max_length=255, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('request_id_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.request')),
            ],
            options={
                'db_table': 'requestdetail',
            },
        ),
    ]
