# Generated by Django 5.0.2 on 2024-04-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_requestdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdetail',
            name='points',
            field=models.TextField(null=True),
        ),
    ]
