# Generated by Django 5.0.2 on 2024-04-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_requestdetail_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isactive_account',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='isvisible_service',
            field=models.BooleanField(default=True),
        ),
    ]
