# Generated by Django 5.0.2 on 2024-04-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_account_isactive_account_service_isvisible_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='isactive_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requestmanager',
            name='status_requestmanager',
            field=models.CharField(choices=[('espera', 'En espera'), ('proceso', 'En proceso'), ('terminado', 'Terminado')], default='espera', max_length=10),
        ),
    ]
