# Generated by Django 5.0.2 on 2024-05-07 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vehicle_isactive_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='isactive_account',
        ),
        migrations.RemoveField(
            model_name='account',
            name='isadmin_account',
        ),
        migrations.AddField(
            model_name='request',
            name='ispriority_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='typevehicle_request',
            field=models.CharField(choices=[('none', 'None'), ('bicycle', 'Bicycle'), ('bike', 'Motorcycle'), ('car', 'Car')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='isactive_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='isadmin_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='issuperadmin_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='isdocument_vehicle',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='isvisible_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user_id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.user'),
        ),
    ]
