# Generated by Django 5.0.2 on 2024-05-08 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_account_isactive_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='user_id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.user'),
        ),
    ]
