# Generated by Django 5.0.2 on 2024-05-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_vehicle_user_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mander',
            name='isactive_mander',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mander',
            name='ishavecar_mander',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mander',
            name='ishavemoto_mander',
            field=models.BooleanField(default=False),
        ),
    ]
