# Generated by Django 5.0.2 on 2024-05-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='user',
            field=models.EmailField(max_length=254),
        ),
    ]
