# Generated by Django 5.0.2 on 2024-05-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_emailverification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
