# Generated by Django 5.0.2 on 2024-05-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_emailverification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email_account',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status_request',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Proceso', 'Proceso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
    ]
