# Generated by Django 5.0.2 on 2024-06-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_account_email_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmanager',
            name='imageprocess_requestmanager',
            field=models.ImageField(blank=True, null=True, upload_to='imgRequestmanager'),
        ),
    ]
